### ISSUE TITLE
Exporting Strings Chokes with Certain Method Names

### ISSUE THREAD

**Issue by PunishedPineapple** [goaaats/CheapLoc#6]
`ExportLocalizable()` throws an exception when there is a function called in the file that has "Localize" in it.  At the bottom is a trivial sample program that reproduces this.  Things work correctly if you change the extension method `GetLocalizedName` to something like `GetTranslatedName`.  The exception thrown reads `System.Exception: Key was empty for message:  (from Program.Main) in CheapLocIssueDemonstrator`

Obviously this can be worked around easily, but it took a while to figure out what was causing the problem, since the "key empty" error was a bit of a red herring.  Idk if it's at least possible to improve the exception message if the issue can't be fixed.

``` csharp
using System;
using CheapLoc;

namespace CheapLocIssueDemonstrator
{
	public class Program
	{
		static void Main( string[] args )
		{
			Loc.SetupWithFallbacks();
			Console.WriteLine( "Trying to export localizeable strings..." );
			try
			{
				string str = HelpWindowPage.General.GetLocalizedName();
				Console.WriteLine( $"Name of enum value: {str}" );
				Loc.ExportLocalizable();
			}
			catch( Exception e )
			{
				Console.WriteLine( e );
			}

			Console.WriteLine( "Type something to exit." );
			Console.ReadLine();
		}
	}

	public enum HelpWindowPage : int
	{
		General,
		Editing,
		Maps,
		Coordinates,
		CircleCalculator
	}

	public static class HelpWindowPageExtensions
	{
		public static string GetLocalizedName( this HelpWindowPage value )
		{
			return value switch
			{
				HelpWindowPage.General => Loc.Localize( "Header: Help Window Page - General", "General" ),
				HelpWindowPage.Editing => Loc.Localize( "Header: Help Window Page - Editing", "Editing" ),
				HelpWindowPage.Maps => Loc.Localize( "Header: Help Window Page - Maps", "Maps" ),
				HelpWindowPage.Coordinates => Loc.Localize( "Header: Help Window Page - Coordinates", "Coordinates" ),
				HelpWindowPage.CircleCalculator => Loc.Localize( "Header: Help Window Page - Circle Calculator", "Circle Calculator" ),
				_ => throw new Exception( $"Unrecognized \"HelpWindowPage\" Enum value \"{value}\"." ),
			};
		}
	}
}
```

**Comment by VariableVixen** [comment]
The [`ExportLocalizableForAssembly`](https://github.com/goaaats/CheapLoc/blob/f8903b60fe0515f15c792cae768fcd2718e8adbc/CheapLoc/Loc.cs#L106) function is doing _something_ at the bytecode level with any calls to methods that have `Localize` in the name. Don't ask me _why_, only goat knows, but that looks like what's breaking here.
